# -*- coding: utf-8 -*-
"""cw_ses4_25bcon1197 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eqjDdercaGeZ7xnHTijdfp5C_UtBypHs
"""

#this is our 4th class
print("hello from collab")



n=5
fact=1
for i in range(1,n+1):
  fact = fact *i
print ("factorial of",n,"is",fact)

n=10
a=0
b=1
for i in range(n):
  print(a)
  next=a+b
  a=b
  b=next

